### ISSUE TITLE
Find a way to enhance the process of adding ne commands

### ISSUE THREAD

**Issue by Saphs** [Saphs/Mp3Bib#14]
Currently the adding of new commands needs you to change three different parts of the code , this should be reduced to one central point.

**Comment by Saphs** [comment]
Will look into the Java reflection API and might already have a solution

**Comment by DanielLiebler** [comment]
reflection is bad..
would rather implement a command as class & interface in communication package and import them on the backend & frontend as hardcoded list. This also reduces security issues
